---
# converge.yml is the playbook file that contains the call for your role.
# Molecule will invoke this playbook with ansible-playbook and run it against an instance created by the driver.
# See: https://molecule.readthedocs.io/en/latest/getting-started/#the-scenario-layout
- name: Converge
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      become: true
      become_user: root

    - name: Debug; print go_user.
      ansible.builtin.debug:
        msg: "Installing/configuring Go for user with username \"{{ go_user }}\""

    - name: Ensure go_user group exists.
      ansible.builtin.group:
        name: "{{ go_user }}"
        state: present
      become: true
      become_user: root

    - name: Ensure go_user user exists.
      ansible.builtin.user:
        append: true
        create_home: true
        group: "{{ go_user }}"
        groups: "{{ go_user }}"
        name: "{{ go_user }}"
      become: true
      become_user: root

  roles:
    - role: librick.go
